title: Jenan Bayati as an Intern in QM – Blog
logo: /assets/LM-logo-lowres-white-orange-ff752f.PNG
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
